apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: {{.Values.mysql.replicaCount}}
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-container
        image: {{.Values.mysql.image}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{.Values.mysql.rootPassword}}
        - name: MYSQL_DATABASE
          value: {{.Values.mysql.database}}
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
