apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: studentapp
    meta.helm.sh/release-namespace: default
    app.kubernetes.io/instance: studentapp  # Add this line to specify the instance
    helm.sh/chart: studentapp-0.1.0  # Update with the actual chart version
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/storage  # Update this path if needed
  storageClassName: standard  # Add this line to specify the storage class
