apiVersion: v1
kind: Service
metadata:
  name: {{.Values.nodePortService.name}}
spec:
  selector:
    app: servlet-app
  ports:
  - protocol: TCP
    port: {{.Values.nodePortService.nodePort}}
    targetPort:  {{.Values.nodePortService.nodePort}}
  type: NodePort
