apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard  # Specify the same storage class as in the PV
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv
