# File: .github/workflows/hello-changes.yml

name: Hello Changes Workflow

# Trigger the workflow on any push event
on:
  push:
    branches:
      - "*" # Triggers on changes in any branch

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print message
        run: echo "Hello, changes!"
